INSERT INTO POSE (poseID, poseName, poseDifficulty, poseInfo, poseIMG) VALUES (1, 'Downward Dog', 'Beginner', 'The body is positioned in an inverted V. Calms the brain and helps relieve stress and mild depression. Energizes the body. Stretches the shoulders, hamstrings, calves, arches, and hands. Strengthens the arms and legs.', 'resources/images/downward_dog.png')
INSERT INTO POSE (poseID, poseName, poseDifficulty, poseInfo, poseIMG) VALUES (2, 'Crow', 'Advanced', 'Separate your knees but keep your feet together. Spread your fingers wide and press your palms and fingertips into the mat. Continue shifting forward until your toes lift up and the full weight of the body is on your arms.', 'resources/images/crow.png')
INSERT INTO POSE (poseID, poseName, poseDifficulty, poseInfo, poseIMG) VALUES (3, 'Child', 'Beginner', 'From a kneeling position, the toes and knees are together with most of the weight of the body resting on the heels of the feet. The arms are extended back resting alongside the legs. The forehead rests softly onto the earth. The gaze is down and inward.', 'resources/images/child_traditional.png')
INSERT INTO POSE (poseID, poseName, poseDifficulty, poseInfo, poseIMG) VALUES (4, 'Tree', 'Intermediate', 'From a standing position, one foot is rooted into the earth with the opposite heel rooted into the inner thigh with the toes pointing toward the earth. The pelvis and the chin are tucked in. The hands come together at the heart in prayer position.', 'resources/images/tree_prayer_R.png')
INSERT INTO POSE (poseID, poseName, poseDifficulty, poseInfo, poseIMG) VALUES (5, 'Warrior I', 'Intermediate', 'The hips are squared. The inner thighs are rotated toward each other. The front knee is bent in a 90-degree angle directly above the ankle. The arms extend up to the sky with the biceps by the ears. The ribcage is lifted and the pelvis tucked.', 'resources/images/warrior_I_L.png')

INSERT INTO ROUTINE (routineID, routineName, routineType) VALUES (1, 'Sun Salutation', 'Warm Up')
INSERT INTO ROUTINE (routineID, routineName, routineType) VALUES (2, 'Moon Salutation', 'Cool Down')

INSERT INTO ROUTINE_POSES (ROUTINE_ID, POSE_ID) VALUES(1,1)
INSERT INTO ROUTINE_POSES (ROUTINE_ID, POSE_ID) VALUES(1,2)
INSERT INTO ROUTINE_POSES (ROUTINE_ID, POSE_ID) VALUES(2,1)